// Alle teksten van het cadeau staan hier. Pas gerust aan.
window.GIFT = {
  name: "Elise",
  from: "Tom",

  // pos = welk deel van de foto zichtbaar blijft in het kader
  photos: [
    { src: "images/26.jpg", pos: "35% 50%" },
    { src: "images/02.jpg", pos: "40% 55%" },
    { src: "images/15.jpg", pos: "50% 65%" },
    { src: "images/01.jpg" },
    { src: "images/27.jpg" },
    { src: "images/20.jpg", pos: "50% 30%" },
    { src: "images/04.jpg" },
    { src: "images/16.jpg", pos: "50% 45%" },
    { src: "images/25.jpg", pos: "50% 35%" },
    { src: "images/06.jpg", pos: "72% 60%" },
    { src: "images/22.jpg", pos: "60% 50%" },
    { src: "images/03.jpg" },
    { src: "images/12.jpg" },
    { src: "images/21.jpg", pos: "50% 30%" },
    { src: "images/11.jpg" },
    { src: "images/18.jpg" },
  ],

  // De dag waarop de timer begon te lopen (jaar-maand-dag)
  together: "2025-03-04",

  // Kaartjes voor de stapel bij "Waarom jij" (de laatste komt als laatste)
  reasons: [
    "Je lacht om mijn domme grapjes. Heel af en toe dan.",
    "Je troost me als ik me rot voel.",
    "Je helpt me elke dag de beste versie van mezelf te worden.",
    "Je bent er elke dag weer voor me.",
    "Met jou wordt zelfs verhuizen een herinnering.",
    "Mijn leven is zoveel beter sinds ik jou ken.",
    "Er gaat geen dag voorbij dat ik niet aan je denk.",
    "Je maakt gewone dagen leuk.",
    "Bij jou kan ik helemaal mezelf zijn.",
    "Je lach. Gewoon, je lach.",
    "Met jou is niks doen nog steeds leuk.",
    "Jouw knuffels zijn de beste van de wereld.",
    "Je gelooft in me, ook als ik dat zelf even niet doe.",
    "Je bent lief, grappig en mooi. Tegelijk. Best oneerlijk eigenlijk.",
    "Je maakt me rustig als het druk is in mijn hoofd.",
    "Ik kan met jou over alles praten.",
    "Thuis is waar jij bent.",
    "Je bent lief, zelfs als ik chagrijnig ben.",
    "Omdat ik elke ochtend blij word als ik aan je denk.",
    "Jij bent het allerbeste wat me ooit is overkomen.",
  ],

  // Filmstrook
  negatives: [
    { src: "images/13.jpg", pos: "40% 55%" },
    { src: "images/19.jpg" },
    { src: "images/17.jpg", pos: "50% 55%" },
    { src: "images/05.jpg" },
    { src: "images/14.jpg", pos: "50% 40%" },
    { src: "images/24.jpg", pos: "50% 58%" },
    { src: "images/07.jpg" },
    { src: "images/23.jpg" },
    { src: "images/08.jpg" },
    { src: "images/09.jpg" },
    { src: "images/10.jpg" },
  ],

  tickets: [
    { title: "Ontbijt op bed" },
    { title: "Filmavond, jij kiest" },
    { title: "Een dagje weg" },
    { title: "Een massage" },
    { title: "Een week de afwas" },
    { title: "Eén keer gelijk krijgen" },
    { title: "Onbeperkt knuffelen" },
    { title: "Samen koken" },
    { title: "Een avond zonder telefoons" },
    { title: "Ik trakteer op ijs" },
    { title: "Uit eten" },
    { title: "Picknick in het park" },
    { title: "Een verrassingsdate" },
    { title: "Een dag lang ja zeggen" },
    { title: "Pannenkoeken bakken" },
    { title: "Spelletjesavond" },
    { title: "Een voetmassage" },
    { title: "Karaoke in de auto" },
    { title: "Jij mag uitslapen" },
    { title: "Ik doe de boodschappen" },
    { title: "Samen naar de bioscoop" },
    { title: "Een lange wandeling" },
    { title: "Iets lekkers halen, ik betaal" },
    { title: "Een knuffel, nu meteen" },
  ],

  note: {
    greeting: "Lieve Elise,",
    body: [
      "Zomaar een cadeautje. Niet omdat het een speciale dag is, maar omdat ik elke dag weer blij ben dat jij er bent.",
      "Een waslijn vol foto's is eigenlijk nog veel te weinig. Er komen er nog heel veel bij, dat beloof ik.",
    ],
    sign: "Liefs, je Tom",
    ps: "P.S. Scroll maar eens terug naar boven. Met het licht aan ziet alles er anders uit.",
  },
};
